// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nimxthgxpkdopyrgqhvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pbXh0aGd4cGtkb3B5cmdxaHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MDA0NTMsImV4cCI6MjA1NTk3NjQ1M30.FrwDivU8V_riIVZ2VnCUtUvVx51zIfnzCfEBYiESs_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);